mod commands;
mod deps;
mod errors;
mod ipc;
mod util;
mod ytdlp;

use tauri_specta::{collect_commands, Builder};

/// Build the tauri-specta command-registration Builder.  Called from `run()`
/// for IPC dispatch and from `tests::export_bindings_up_to_date()` to
/// regenerate `src/bindings.ts`.  Single source of truth: every command listed
/// here is the complete IPC surface.
fn make_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::formats::fetch_formats,
        commands::download::resolve_queue,
        commands::queue::enqueue_download,
        commands::queue::enqueue_batch,
        commands::queue::cancel_task,
        commands::queue::pause_task,
        commands::queue::resume_task,
        commands::queue::set_concurrency,
        commands::queue::snapshot_tasks,
        commands::settings::load_settings,
        commands::settings::save_settings,
        commands::deps::check_ytdlp_version_cmd,
        commands::deps::check_ffmpeg_version_cmd,
        commands::deps::check_deno_version_cmd,
        commands::deps::check_latest_release_cmd,
        commands::deps::download_ytdlp_update_cmd,
        commands::log::write_log,
        commands::log::read_log,
    ])
}

/// Record any panic's location + message to app.log before the process dies.
/// A windowed release build has no console, and a panic crossing Tauri's
/// IPC/FFI boundary aborts the process (Windows 0xc0000409) with no trace —
/// this leaves a breadcrumb in app.log so field crashes are diagnosable.
fn install_panic_logger() {
    let default_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(move |info| {
        let loc = info
            .location()
            .map(|l| format!("{}:{}", l.file(), l.line()))
            .unwrap_or_else(|| "unknown".into());
        let msg = info
            .payload()
            .downcast_ref::<&str>()
            .map(|s| (*s).to_string())
            .or_else(|| info.payload().downcast_ref::<String>().cloned())
            .unwrap_or_else(|| "<non-string panic payload>".into());
        crate::commands::log::write_log("ERROR".into(), format!("PANIC at {loc}: {msg}"));
        default_hook(info);
    }));
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    install_panic_logger();
    let builder = make_builder();

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            // Cache Tauri's resource dir BEFORE any binary lookup so util.rs
            // can find the bundled binaries, which `resources` bundling places
            // under the resource dir (not next to the exe) on Linux packages.
            use tauri::Manager;
            let rd = app.path().resource_dir().ok();
            crate::util::set_resource_dir(rd);
            // `resources` bundling may strip the +x bit on Linux; make the
            // bundled tools executable before anything tries to spawn them.
            crate::util::ensure_bundled_executables();
            // Restore persisted queue (Rust owns queue.json now — frontend is
            // a read-only view that hydrates from emitted task:state events).
            let handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                commands::queue::load_queue_on_startup(handle);
            });
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");

    commands::queue::kill_all_on_exit();
    commands::queue::wait_all_on_exit();
}

#[cfg(test)]
mod tests {
    /// Regenerate `src/bindings.ts` from the live tauri-specta Builder.  CI
    /// runs this via `cargo test` then asserts `git diff --exit-code` on the
    /// file; locally just re-run `cargo test` whenever Rust IPC signatures
    /// change and commit the diff.
    #[test]
    fn export_bindings_up_to_date() {
        let builder = super::make_builder();
        let target = concat!(env!("CARGO_MANIFEST_DIR"), "/../src/bindings.ts");
        builder
            .export(
                specta_typescript::Typescript::default()
                    .bigint(specta_typescript::BigIntExportBehavior::Number)
                    .header("// @ts-nocheck — auto-generated by tauri-specta\n"),
                target,
            )
            .expect("failed to export typescript bindings");
    }
}
