// @ts-nocheck — auto-generated by tauri-specta

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async fetchFormats(url: string, net: NetworkOptions) : Promise<Result<FormatList, ErrorKind>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_formats", { url, net }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a list of URLs (including playlists) into individual QueueEntry items.
 * Playlist URLs (a `/playlist` page) are expanded via `yt-dlp --flat-playlist`.
 * A `watch?v=X&list=Y` URL is treated as the single video X (its task carries
 * `--no-playlist`), so pasting one video from a playlist doesn't pull the lot.
 * Returns deduplicated entries; non-http URLs are silently dropped (the frontend
 * filters them up-front so this is defense-in-depth).
 */
async resolveQueue(urls: string[], net: NetworkOptions) : Promise<Result<QueueEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_queue", { urls, net }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async enqueueDownload(id: string, params: DownloadParams) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enqueue_download", { id, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enqueue many tasks in one IPC call. Used for playlist / multi-URL paste so a
 * 200-item batch is a single lock acquisition + one disk save + one scheduler
 * pass, instead of N round-trips that each spawn their own save.
 * Returns the number actually accepted; invalid URLs, duplicate ids and items
 * past `MAX_QUEUE_DEPTH` are skipped.
 */
async enqueueBatch(items: BatchItem[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enqueue_batch", { items }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelTask(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pause a running task: arm the pause flag and kill its child. yt-dlp leaves a
 * `.part` file behind, and the runner's finalize moves the task into the paused
 * map (status Paused) instead of Failed. No-op for non-running ids.
 */
async pauseTask(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume a paused task: move it back to pending (front, so it starts next) and
 * kick the scheduler. The re-spawned yt-dlp continues from the `.part` file via
 * its default `--continue`. No-op for ids that aren't paused.
 */
async resumeTask(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setConcurrency(n: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_concurrency", { n }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async snapshotTasks() : Promise<Task[]> {
    return await TAURI_INVOKE("snapshot_tasks");
},
async loadSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkYtdlpVersionCmd() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_ytdlp_version_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkFfmpegVersionCmd() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_ffmpeg_version_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkDenoVersionCmd() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_deno_version_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkLatestReleaseCmd() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_latest_release_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadYtdlpUpdateCmd() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_ytdlp_update_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeLog(level: string, message: string) : Promise<void> {
    await TAURI_INVOKE("write_log", { level, message });
},
/**
 * Read the most recent N lines of app.log (default 200, max 1000).
 */
async readLog(tail: number | null) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_log", { tail }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Typed mirror of the frontend's settings store. `camelCase` to match
 * what the existing settings.json on disk already uses (frontend wrote it).
 * `#[serde(default)]` makes missing fields fall back to Default so the file
 * remains forward / backward compatible.
 */
export type AppSettings = { theme: string; language: string; downloadDir: string; filenameTemplate: string; concurrency: number; cookieSource: string; cookieFilePath: string; proxy: string; rateLimit: string; preferredCodec: string; maxHeight: number }
export type BatchItem = { id: string; params: DownloadParams }
export type DownloadParams = { url: string; title: string; thumbnail: string; videoFormatId: string | null; audioFormatId: string | null; outputDir: string; cookieSource: string; cookieFilePath: string; proxy: string; rateLimit: string; filenameTemplate: string; 
/**
 * Max video height for Best-Quality / batch downloads (0 = unlimited).
 */
maxHeight: number; 
/**
 * Preferred video codec ("any" | "h264" | "vp9" | "av1") for Best-Quality.
 */
preferredCodec: string }
/**
 * Classified error type from yt-dlp stderr output.
 * 
 * Used by `commands::formats::fetch_formats` to turn a failed parse into a
 * structured error that the frontend can localize. The download path no longer
 * surfaces per-task error detail (terminal tasks are notification-only), so
 * there is intentionally no user-message/reasons/suggestions builder here.
 */
export type ErrorKind = 
/**
 * 403, bot detection, "Sign in to confirm you're not a bot"
 */
{ kind: "RateLimited" } | 
/**
 * 404, "not available", private, deleted
 */
{ kind: "VideoUnavailable" } | 
/**
 * timeout, connection refused, DNS resolve failure
 */
{ kind: "NetworkTimeout" } | 
/**
 * cookies expired, invalid cookies
 */
{ kind: "CookieExpired" } | 
/**
 * disk full, quota exceeded, no space
 */
{ kind: "DiskFull" } | 
/**
 * Any unrecognized error pattern; contains a sanitized snippet
 */
{ kind: "Unknown"; message: string }
export type FormatInfo = { id: string; label: string; resolution: string; codec: string; filesize: string; ext: string; height: number; fps: number; 
/**
 * Underlying byte count (0 if unknown). Sort key; not displayed.
 */
sizeBytes: number; 
/**
 * True if the format carries both video and audio (no merge needed).
 */
muxed: boolean }
export type FormatList = { title: string; channel: string; duration: string; thumbnail: string; videoFormats: FormatInfo[]; audioFormats: FormatInfo[] }
/**
 * Cookie + proxy options shared by every yt-dlp invocation that talks to the
 * network: download, `fetch_formats` and `resolve_queue`. Without threading
 * these into format-fetch / playlist-expansion, cookie-gated (YouTube bot
 * check) or proxy-gated (region lock) content fails to even list formats while
 * the actual download would have succeeded.
 */
export type NetworkOptions = { cookieSource: string; cookieFilePath: string; proxy: string }
export type QueueEntry = { url: string; title: string }
export type Task = { id: string; status: TaskStatus; params: DownloadParams; percent: number; speed: string; eta: string; 
/**
 * Monotonic insertion ordinal. Stable sort key so snapshots (and the
 * restored queue) keep chronological order rather than HashMap iteration
 * order. Persisted; restored values are honored (see load_queue_on_startup).
 */
seq: number }
export type TaskStatus = "pending" | "running" | "paused" | "complete" | "failed" | "cancelled"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
